### ISSUE TITLE
Qmap - Dozer #1958 on Singapore server - Change of Base currency from USD to SGD

### ISSUE THREAD

**Issue by shalinibajaj-qapita** [shalinibajaj-qapita/Shalini#1]

**Comment by shruti-ps** [comment]
Done in prod

**Comment by shruti-ps** [comment]
curl --location --request PUT 'https://captable.qapitacorp.com/api/v1/issuers/1/base-currency' \
--header 'Authorization: Bearer sampleToken' \
--header 'Content-Type: application/json' \
--data-raw '"SGD" //New currency we are changing to'
